server:
  port: 8080

spring:
  application:
    name: demo-app

  datasource:
    url: jdbc:h2:mem:demo-db
    driverClassName: org.h2.Driver
    username: jezz
    password: changeit
    initialization-mode: embedded # initialize script only when is in-memory db

  sql:
    init:
      data-locations: classpath:init-data-in-memory.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC-3
    show-sql: true # query-log
    hibernate.ddl-auto: update # update schemas
    defer-datasource-initialization: true # delay datasource initialization to load data

  h2:
    console:
      enabled: true # h2 web console
      path: /demo-app-db-ui # h2 web console url | default path: h2-console

springdoc:
  api-docs.path: /demo-app-docs
  swagger-ui:
    path: /demo-app-ui.html # swagger ui url
    enabled: true
